theme: jekyll-theme-modernist
title: Welcome to Nicole Aguilera's homepage!
description: Feel free to browse and view what projects I have been working on!

layout: page
title: "Contact Me"
permalink: /contact/
